# Generated by Django 4.2.25 on 2026-01-29 15:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_level', models.CharField(choices=[('standard', 'Standard (1.0x)'), ('strong', 'Strong (1.5x)'), ('high', 'High (2.0x)'), ('exceptional', 'Exceptional (3.0x)')], default='standard', max_length=20)),
                ('deliverable', models.CharField(blank=True, default='', max_length=200)),
                ('is_running', models.BooleanField(default=False)),
                ('current_start_at', models.DateTimeField(blank=True, null=True)),
                ('accumulated_minutes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goals.category')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_timer', to='goals.goal')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wake_at', models.DateTimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_day', to='goals.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('quality_level', models.CharField(choices=[('standard', 'Standard (1.0x)'), ('strong', 'Strong (1.5x)'), ('high', 'High (2.0x)'), ('exceptional', 'Exceptional (3.0x)')], default='standard', max_length=20)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('effective_minutes', models.PositiveIntegerField(default=0)),
                ('mae_block', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=20)),
                ('deliverable', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='goals.category')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='goals.goal')),
            ],
            options={
                'indexes': [models.Index(fields=['start_at'], name='tracker_ses_start_a_86ee03_idx'), models.Index(fields=['category', 'start_at'], name='tracker_ses_categor_53ca32_idx'), models.Index(fields=['goal', 'start_at'], name='tracker_ses_goal_id_1e7b83_idx'), models.Index(fields=['quality_level'], name='tracker_ses_quality_22a681_idx')],
            },
        ),
    ]
