# Generated by Django 5.2.11 on 2026-02-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_workitem'),
        ('tracker', '0002_activeday_sleep_at_activeday_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['archived', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='goals.workitem'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='tracker.taggroup')),
            ],
            options={
                'ordering': ['group_id', 'archived', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SessionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tags', to='tracker.session')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_tags', to='tracker.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['session'], name='tracker_ses_session_5e94f6_idx'), models.Index(fields=['tag'], name='tracker_ses_tag_id_a75310_idx')],
                'unique_together': {('session', 'tag')},
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['group', 'archived', 'sort_order', 'name'], name='tracker_tag_group_i_ded5ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('group', 'name')},
        ),
    ]
