# Generated by Django 4.2.25 on 2026-01-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_key', models.DateField()),
                ('wake_at', models.DateTimeField()),
                ('sleep_at', models.DateTimeField()),
                ('rating', models.CharField(default='unknown', max_length=32)),
                ('reflection', models.CharField(blank=True, default='', max_length=240)),
                ('raw_minutes', models.PositiveIntegerField(default=0)),
                ('effective_minutes', models.PositiveIntegerField(default=0)),
                ('exceptional_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_snapshots', to='goals.goal')),
            ],
            options={
                'indexes': [models.Index(fields=['day_key'], name='snapshots_d_day_key_f1c965_idx')],
                'unique_together': {('goal', 'day_key')},
            },
        ),
    ]
