# Generated by Django 4.2.25 on 2026-01-29 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_trackersettings_enforce_active_day_bounds_and_more'),
        ('snapshots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('days_count', models.PositiveIntegerField(default=0)),
                ('raw_minutes', models.PositiveIntegerField(default=0)),
                ('effective_minutes', models.PositiveIntegerField(default=0)),
                ('target_minutes', models.PositiveIntegerField(default=0)),
                ('raw_pct', models.FloatField(default=0.0)),
                ('effective_pct', models.FloatField(default=0.0)),
                ('rating', models.CharField(default='Good', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.AlterModelOptions(
            name='daysnapshot',
            options={'ordering': ['-day_key']},
        ),
        migrations.AddField(
            model_name='daysnapshot',
            name='effective_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='daysnapshot',
            name='raw_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='daysnapshot',
            name='sessions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daysnapshot',
            name='target_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daysnapshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='daysnapshot',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_snapshots', to='goals.goal'),
        ),
        migrations.AlterField(
            model_name='daysnapshot',
            name='rating',
            field=models.CharField(default='Good', max_length=20),
        ),
        migrations.AlterField(
            model_name='daysnapshot',
            name='reflection',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='daysnapshot',
            index=models.Index(fields=['goal', 'day_key'], name='snapshots_d_goal_id_77acfe_idx'),
        ),
        migrations.AddField(
            model_name='weeksnapshot',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_snapshots', to='goals.goal'),
        ),
        migrations.AddIndex(
            model_name='weeksnapshot',
            index=models.Index(fields=['goal', 'week_start'], name='snapshots_w_goal_id_8d19c4_idx'),
        ),
        migrations.AddIndex(
            model_name='weeksnapshot',
            index=models.Index(fields=['week_start'], name='snapshots_w_week_st_4b1121_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeksnapshot',
            unique_together={('goal', 'week_start')},
        ),
    ]
