# Generated by Django 4.2.25 on 2026-01-29 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_target_minutes', models.PositiveIntegerField(default=19800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_bedtime', models.TimeField(default=datetime.time(23, 59))),
                ('daily_target_minutes', models.PositiveIntegerField(default=660)),
                ('net_points_cap', models.IntegerField(default=4)),
                ('mae_noon_cutoff', models.TimeField(default=datetime.time(12, 0))),
                ('mae_evening_cutoff', models.TimeField(default=datetime.time(17, 0))),
                ('exceptional_min_minutes', models.PositiveIntegerField(default=45)),
                ('exceptional_max_per_day', models.PositiveIntegerField(default=2)),
            ],
        ),
    ]
