# Generated by Django 4.2.25 on 2026-01-29 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
