# Generated by Django 4.2.25 on 2026-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_duration_days_goal_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackersettings',
            name='enforce_active_day_bounds',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trackersettings',
            name='monthly_target_minutes',
            field=models.PositiveIntegerField(default=19800),
        ),
    ]
