# Generated by Django 5.2.11 on 2026-02-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_trackersettings_enforce_active_day_bounds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('blocked', 'Blocked')], default='planned', max_length=20)),
                ('planned_minutes', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='goals.goal')),
            ],
            options={
                'ordering': ['archived', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['goal', 'status'], name='goals_worki_goal_id_eb1ae8_idx'), models.Index(fields=['archived', 'sort_order', 'name'], name='goals_worki_archive_353687_idx')],
            },
        ),
    ]
